# https://mpd.readthedocs.io/en/stable/user.html#compiling-from-source
- name: Install latest MPD from GitHub
  hosts: servers
  tasks:
    - name: Ensure Git
      become: true
      ansible.builtin.package:
        name: git
        state: latest
    - name: Download latest MPD
      ansible.builtin.git:
        repo: https://github.com/MusicPlayerDaemon/MPD.git
        version: v0.23.13
        depth: 1
        dest: /home/snapcast/mpd
    - name: Ensure MPD dependencies
      become: true
      ansible.builtin.package:
        name:
          - meson
          - g++
          - libfmt-dev
          - libpcre2-dev
          - libmad0-dev
          - libmpg123-dev
          - libid3tag0-dev
          - libflac-dev
          - libvorbis-dev
          - libopus-dev
          - libogg-dev
          - libadplug-dev
          - libaudiofile-dev
          - libsndfile1-dev
          - libfaad-dev
          - libfluidsynth-dev
          - libgme-dev
          - libmikmod-dev
          - libmodplug-dev
          - libmpcdec-dev
          - libwavpack-dev
          - libwildmidi-dev
          - libsidplay2-dev
          - libsidutils-dev
          - libresid-builder-dev
          - libavcodec-dev
          - libavformat-dev
          - libmp3lame-dev
          - libtwolame-dev
          - libshine-dev
          - libsamplerate0-dev
          - libsoxr-dev
          - libbz2-dev
          - libcdio-paranoia-dev
          - libiso9660-dev
          - libmms-dev
          - libzzip-dev
          - libcurl4-gnutls-dev
          - libyajl-dev
          - libexpat-dev
          - libasound2-dev
          - libao-dev
          - libjack-jackd2-dev
          - libopenal-dev
          - libpulse-dev
          - libshout3-dev
          - libsndio-dev
          - libmpdclient-dev
          - libnfs-dev
          - libupnp-dev
          - libavahi-client-dev
          - libsqlite3-dev
          - libsystemd-dev
          - libgtest-dev
          - libboost-dev
          - libicu-dev
          - libchromaprint-dev
          - libgcrypt20-dev
        state: latest
    - name: Configure Meson
      ansible.builtin.command:
        chdir: /home/snapcast/mpd
        cmd: meson . output/release --buildtype=debugoptimized -Db_ndebug=true -Dsysconfdir='/etc'
    - name: Compile
      ansible.builtin.command:
        chdir: /home/snapcast/mpd
        cmd: ninja -C output/release
    - name: Install
      become: true
      ansible.builtin.command:
        chdir: /home/snapcast/mpd
        cmd: ninja -C output/release install
    - name: Restart MPD
      become: true
      ansible.builtin.service:
        name: mpd
        state: restarted
